# SET SERVER PORT
server.port: ${PORT:8080}

# CONNECT TO IBM WATSON
ibm.assistant.version.date: "2019-03-26"
ibm.assistant.workspace.id: 40bbc08c-ae31-4928-b43c-81c12037640d
ibm.assistant.username: apikey
ibm.assistant.password: gboa0c6uwxtDJPYbfmkhWl881XveA8YA027Wkl6cVqzX

# CONNECT TO HEROKU DATABASE
#spring.jpa.show-sql: "true"
#spring.datasource.url: jdbc:mysql://us-cdbr-iron-east-03.cleardb.net/heroku_555f66199199af3?reconnect=true
#spring.datasource.username: b56c555d260053
#spring.datasource.password: ab87394d
#spring.jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
#spring.jpa.hibernate.ddl-auto: update

# DATABASE TO MAIL BACKUP
spring.mail.host: smtp.gmail.com
spring.mail.port: "587"
spring.mail.username: chatbotwatson1@gmail.com
spring.mail.password: NokiaChatbot1
spring.mail.properties.mail.smtp.auth: "true"
spring.mail.properties.mail.smtp.starttls.enable: "true"

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 5014057553-8gm9um6vnli3cle5rgigcdjpdrid14m9.apps.googleusercontent.com
            clientSecret: tWZKVLxaD_ARWsriiiUFYoIk
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
            - email
            - profile
          facebook:
            clientId: 121189305185277
            clientSecret: 42ffe5aa7379e8326387e0fe16f34132
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
            - email
            - public_profile
          github:
            clientId: d3e47fc2ddd966fa4352
            clientSecret: 3bc0f6b8332f93076354c2a5bada2f5a05aea60d
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
            - user:email
            - read:user
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the frontend client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
    - http://localhost:3000/oauth2/redirect
    - myandroidapp://oauth2/redirect
    - myiosapp://oauth2/redirect